회전, 키스, 오른쪽 끝으로 이동, 아래로 이동
Space-Belt/blockcoaster pull request #5
Opened 2024-03-12 20:04 UTC by Space-Belt

2024-03-13 04:02 UTC, hoonjoo-park requested changes

2024-03-13 04:02 UTC, hoonjoo-park commented on src/components/reanimated/HorizontalMove.tsx
> +      transform: [{translateX: (-71 * position.value) / 100}],
71은 컴포넌트 밖에 상수로 빼서 활용하는게 좋을 것 같습니다. 
ex) const ICON_WIDTH  = 71

2024-03-13 04:02 UTC, hoonjoo-park commented on src/screens/LearnAnimationScreen.tsx
> +const DEFAULT_DEGREE = 0;
오잉? 이건 왜 밖에 빼놓으셨나요

2024-03-13 04:02 UTC, hoonjoo-park commented on src/screens/LearnAnimationScreen.tsx
> +  React.useEffect(() => {}, []);
삭제해도 될 것 같네요

2024-03-13 04:02 UTC, hoonjoo-park commented on src/screens/LearnAnimationScreen.tsx
> +    },
이런 10 같은 것은 
컴포넌트 밖으로 상수로 빼서 사용하는게 더 가독성 및 유지보수 측면에서 좋을 것 같습니다

2024-03-13 04:02 UTC, hoonjoo-park commented on src/screens/LearnAnimationScreen.tsx
> +      {
근데 그냥 이렇게 firstSwitch, secondSwitch로 구분할 바에는
두 컴포넌트를 아예 분리하는 것도 좋았을 것 같습니다

2024-03-13 04:02 UTC, hoonjoo-park commented on src/screens/LearnAnimationScreen.tsx
> +  const kissAnimatedStyle = (direction: string) =>
이런 경우는 타입을 direction: 'left' | 'right'로 하면 더 좋습니다

2024-03-15 08:31 UTC, Space-Belt commented on src/screens/LearnAnimationScreen.tsx
> +const DEFAULT_DEGREE = 0;
안에 넣는게 좋은가요?

2024-03-15 08:35 UTC, Space-Belt commented on src/screens/LearnAnimationScreen.tsx
> +      {
아 맞습니다..!

2024-03-18 17:02 UTC, merged